/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists/index'
import { Route as AuthenticatedListsNewRouteImport } from './routes/_authenticated/lists/new'
import { Route as AuthenticatedListsListIdRouteImport } from './routes/_authenticated/lists/$listId'
import { Route as AuthenticatedListsListIdDeleteRouteImport } from './routes/_authenticated/lists/$listId/delete'
import { Route as AuthenticatedListsListIdTasksNewRouteImport } from './routes/_authenticated/lists/$listId/tasks/new'
import { Route as AuthenticatedListsListIdTasksTaskIdDeleteRouteImport } from './routes/_authenticated/lists/$listId/tasks/$taskId/delete'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsNewRoute = AuthenticatedListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsListIdRoute =
  AuthenticatedListsListIdRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListsListIdDeleteRoute =
  AuthenticatedListsListIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedListsListIdRoute,
  } as any)
const AuthenticatedListsListIdTasksNewRoute =
  AuthenticatedListsListIdTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => AuthenticatedListsListIdRoute,
  } as any)
const AuthenticatedListsListIdTasksTaskIdDeleteRoute =
  AuthenticatedListsListIdTasksTaskIdDeleteRouteImport.update({
    id: '/tasks/$taskId/delete',
    path: '/tasks/$taskId/delete',
    getParentRoute: () => AuthenticatedListsListIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lists/$listId': typeof AuthenticatedListsListIdRouteWithChildren
  '/lists/new': typeof AuthenticatedListsNewRoute
  '/lists/': typeof AuthenticatedListsIndexRoute
  '/lists/$listId/delete': typeof AuthenticatedListsListIdDeleteRoute
  '/lists/$listId/tasks/new': typeof AuthenticatedListsListIdTasksNewRoute
  '/lists/$listId/tasks/$taskId/delete': typeof AuthenticatedListsListIdTasksTaskIdDeleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lists/$listId': typeof AuthenticatedListsListIdRouteWithChildren
  '/lists/new': typeof AuthenticatedListsNewRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/lists/$listId/delete': typeof AuthenticatedListsListIdDeleteRoute
  '/lists/$listId/tasks/new': typeof AuthenticatedListsListIdTasksNewRoute
  '/lists/$listId/tasks/$taskId/delete': typeof AuthenticatedListsListIdTasksTaskIdDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/lists/$listId': typeof AuthenticatedListsListIdRouteWithChildren
  '/_authenticated/lists/new': typeof AuthenticatedListsNewRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
  '/_authenticated/lists/$listId/delete': typeof AuthenticatedListsListIdDeleteRoute
  '/_authenticated/lists/$listId/tasks/new': typeof AuthenticatedListsListIdTasksNewRoute
  '/_authenticated/lists/$listId/tasks/$taskId/delete': typeof AuthenticatedListsListIdTasksTaskIdDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/lists/$listId'
    | '/lists/new'
    | '/lists/'
    | '/lists/$listId/delete'
    | '/lists/$listId/tasks/new'
    | '/lists/$listId/tasks/$taskId/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/lists/$listId'
    | '/lists/new'
    | '/lists'
    | '/lists/$listId/delete'
    | '/lists/$listId/tasks/new'
    | '/lists/$listId/tasks/$taskId/delete'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/lists/$listId'
    | '/_authenticated/lists/new'
    | '/_authenticated/lists/'
    | '/_authenticated/lists/$listId/delete'
    | '/_authenticated/lists/$listId/tasks/new'
    | '/_authenticated/lists/$listId/tasks/$taskId/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/new': {
      id: '/_authenticated/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof AuthenticatedListsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$listId': {
      id: '/_authenticated/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AuthenticatedListsListIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$listId/delete': {
      id: '/_authenticated/lists/$listId/delete'
      path: '/delete'
      fullPath: '/lists/$listId/delete'
      preLoaderRoute: typeof AuthenticatedListsListIdDeleteRouteImport
      parentRoute: typeof AuthenticatedListsListIdRoute
    }
    '/_authenticated/lists/$listId/tasks/new': {
      id: '/_authenticated/lists/$listId/tasks/new'
      path: '/tasks/new'
      fullPath: '/lists/$listId/tasks/new'
      preLoaderRoute: typeof AuthenticatedListsListIdTasksNewRouteImport
      parentRoute: typeof AuthenticatedListsListIdRoute
    }
    '/_authenticated/lists/$listId/tasks/$taskId/delete': {
      id: '/_authenticated/lists/$listId/tasks/$taskId/delete'
      path: '/tasks/$taskId/delete'
      fullPath: '/lists/$listId/tasks/$taskId/delete'
      preLoaderRoute: typeof AuthenticatedListsListIdTasksTaskIdDeleteRouteImport
      parentRoute: typeof AuthenticatedListsListIdRoute
    }
  }
}

interface AuthenticatedListsListIdRouteChildren {
  AuthenticatedListsListIdDeleteRoute: typeof AuthenticatedListsListIdDeleteRoute
  AuthenticatedListsListIdTasksNewRoute: typeof AuthenticatedListsListIdTasksNewRoute
  AuthenticatedListsListIdTasksTaskIdDeleteRoute: typeof AuthenticatedListsListIdTasksTaskIdDeleteRoute
}

const AuthenticatedListsListIdRouteChildren: AuthenticatedListsListIdRouteChildren =
  {
    AuthenticatedListsListIdDeleteRoute: AuthenticatedListsListIdDeleteRoute,
    AuthenticatedListsListIdTasksNewRoute:
      AuthenticatedListsListIdTasksNewRoute,
    AuthenticatedListsListIdTasksTaskIdDeleteRoute:
      AuthenticatedListsListIdTasksTaskIdDeleteRoute,
  }

const AuthenticatedListsListIdRouteWithChildren =
  AuthenticatedListsListIdRoute._addFileChildren(
    AuthenticatedListsListIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedListsListIdRoute: typeof AuthenticatedListsListIdRouteWithChildren
  AuthenticatedListsNewRoute: typeof AuthenticatedListsNewRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedListsListIdRoute: AuthenticatedListsListIdRouteWithChildren,
  AuthenticatedListsNewRoute: AuthenticatedListsNewRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
